//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitayGorod_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChitayGorod_projectEntities : DbContext
    {
        public ChitayGorod_projectEntities()
            : base("name=ChitayGorod_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BooksSet> BooksSet { get; set; }
        public virtual DbSet<PosetitelSet> PosetitelSet { get; set; }
        public virtual DbSet<ProdavecSet> ProdavecSet { get; set; }
        public virtual DbSet<UchetProdSet> UchetProdSet { get; set; }
    }
}
