//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitayGorod_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class UchetProdSet
    {
        public int Id { get; set; }
        public int IdPosetitel { get; set; }
        public int IdProdavec { get; set; }
        public int IdBook { get; set; }
    
        public virtual BooksSet BooksSet { get; set; }
        public virtual PosetitelSet PosetitelSet { get; set; }
        public virtual ProdavecSet ProdavecSet { get; set; }
    }
}
